# Environment Configuration for Bazar Infrastructure
# This file defines the configuration for different environments

environments:
  dev:
    name: "DEV"
    description: "Development Environment"
    vpc:
      cidr: "10.0.0.0/16"
      public_subnet1_cidr: "10.0.2.0/24"
      public_subnet2_cidr: "10.0.3.0/24"
      private_app_subnet_cidr: "10.0.10.0/24"
      private_data_subnet1_cidr: "10.0.20.0/24"
      private_data_subnet2_cidr: "10.0.30.0/24"
    compute:
      ecs_cpu: "256"
      ecs_memory: "512"
      ecs_desired_count: 1
      ecs_max_count: 2
    database:
      instance_class: "db.t3.micro"
      allocated_storage: 20
      multi_az: false
      backup_retention: 7
    tags:
      Environment: "DEV"
      Project: "Bazar"
      Owner: "DevOps"
      CostCenter: "Development"

  prod:
    name: "PROD"
    description: "Production Environment"
    vpc:
      cidr: "10.1.0.0/16"
      public_subnet1_cidr: "10.1.2.0/24"
      public_subnet2_cidr: "10.1.3.0/24"
      private_app_subnet1_cidr: "10.1.10.0/24"
      private_data_subnet1_cidr: "10.1.20.0/24"
      private_data_subnet2_cidr: "10.1.30.0/24"
    compute:
      ecs_cpu: "512"
      ecs_memory: "1024"
      ecs_desired_count: 2
      ecs_max_count: 4
    database:
      instance_class: "db.t3.small"
      allocated_storage: 100
      multi_az: true
      backup_retention: 30
    tags:
      Environment: "PROD"
      Project: "Bazar"
      Owner: "DevOps"
      CostCenter: "Production" 